[package]
name = "Vindskrivare"
description = "Pro version of the IKEA Vindstyrka using the same SEN55 sensor but exposing pm1.0, pm2.5, pm4, pm10, VOC, NOx, Temperature and Humidity over MQTT"
version = "0.1.0"
edition = "2021"

[dependencies]
