[profile.release]
# Allows defmt to display log locations even in release
debug = true

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = [
    "probe-rs",
    "run",
    "--chip",
    "RP2040",
    "--log-format",
    "{L} {f:>10}: {s}",
]

[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "info"
